### ISSUE TITLE
immutable configuration

### ISSUE THREAD

**Issue by chuckbutler** [jaywink/diaspora-juju#18]
The hostname configuration option is immutable - and this does not conform to the charm store policy. Is there a potential work-around to make this configuration option mutable and able to change post installation?

This is set in the apache vhost configuration - are there other locations that require the update?

**Comment by jaywink** [comment]
Hi, sorry for not noticing your issue earlier.

diaspora* itself does **not** allow changing hostname, after installation. It simple does not work. The reason is that diaspora* pods can be thought of something like email servers. If you change the hostname, you are basically breaking relations to everything in the diaspora* network. All the linkages will be broken and communication will work only outwards.

I realize this might not sit into charm store policies, but unfortunately it is something that needs to be enforced by the charms as otherwise pods can be broken via a simple config change. The correct solution I guess would be to allow changing it, but then raise an error in the `config-changed` hook and not implement the change internally. But IMHO, it would only add unnecessary complexity just to satisfy charm policies :)

Thanks for the note anyway!
